---
name: PlatformIO CI

on:
  schedule:
    - cron: '0 21 2-6 * *'
  push:
    branches: ["master"]
    paths:
      - 'src/**/*'
      - 'include/**/*'
      - 'data/**/*'
  pull_request:
    branches: ["master"]
    paths:
      - 'src/**/*'
      - 'include/**/*'
      - 'data/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/absoluteXYZ.ino]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci --lib="." lib_deps="git+https://github.com/homieiot/homie-esp8266.git#develop git+https://github.com/kitesurfer1404/WS2812FX.git#master"--board=esp01_1m
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
